### ISSUE TITLE
KeyError: 1040

### ISSUE THREAD

**Issue by harliquin** [dirkjanm/ldapdomaindump#17] opened 2019-02-20 15:48 UTC
Just tried ldapdomaindump and getting this error.  I have tried it with and without --minimal and other options.
(I replaced real data here with generic)

ldapdomaindump -u domain\\user -p "password" --minimal  (IP of AD)
[*] Connecting to host...
[*] Binding to host
[+] Bind OK
[*] Starting domain dump
Traceback (most recent call last):
  File "/usr/local/bin/ldapdomaindump", line 4, in <module>
    __import__('pkg_resources').run_script('ldapdomaindump==0.9.1', 'ldapdomaindump')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ldapdomaindump-0.9.1-py2.7.egg/EGG-INFO/scripts/ldapdomaindump", line 3, in <module>
    ldapdomaindump.main()
  File "/usr/local/lib/python2.7/dist-packages/ldapdomaindump-0.9.1-py2.7.egg/ldapdomaindump/__init__.py", line 922, in main
    dd.domainDump()
  File "/usr/local/lib/python2.7/dist-packages/ldapdomaindump-0.9.1-py2.7.egg/ldapdomaindump/__init__.py", line 414, in domainDump
    rw.generateUsersReport(self)
  File "/usr/local/lib/python2.7/dist-packages/ldapdomaindump-0.9.1-py2.7.egg/ldapdomaindump/__init__.py", line 769, in generateUsersReport
    html = self.generateHtmlTable(dd.users, self.userattributes, 'Domain users')
  File "/usr/local/lib/python2.7/dist-packages/ldapdomaindump-0.9.1-py2.7.egg/ldapdomaindump/__init__.py", line 503, in generateHtmlTable
    of.append('<td>%s</td>' % self.formatAttribute(li[att], liIsGroup))
  File "/usr/local/lib/python2.7/dist-packages/ldapdomaindump-0.9.1-py2.7.egg/ldapdomaindump/__init__.py", line 597, in formatAttribute
    return self.formatGroupsHtml([self.dd.groups_dnmap[att.value]])
KeyError: 1040

**Comment by dirkjanm** [comment] 2019-04-06 16:51
I'm not sure if you can still test this, but it should be fixed now. 
The cause was most likely a group that didn't exist anymore or we somehow didn't have permissions to query.

**Closed** 2019-04-06 16:50 UTC
