### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by grease082** [dirkjanm/ldapdomaindump#26] opened 2020-02-06 11:26 UTC
Hi, I get the following exception when using the tool: 
`
[*] Connecting as anonymous user, dumping will probably fail. Consider specifying a username/password to login with   
[*] Connecting to host...   
[*] Binding to host   
[+] Bind OK  
[*] Starting domain dump
Traceback (most recent call last):
  File "ldapdomaindump.py", line 3, in <module>
    ldapdomaindump.main()
  File "/root/Downloads/ldapdomaindump/ldapdomaindump/__init__.py", line 944, in main
    dd.domainDump()
  File "/root/Downloads/ldapdomaindump/ldapdomaindump/__init__.py", line 422, in domainDump
    rw.generateUsersReport(self)
  File "/root/Downloads/ldapdomaindump/ldapdomaindump/__init__.py", line 789, in generateUsersReport
    dd.mapGroupsIdsToDns()
  File "/root/Downloads/ldapdomaindump/ldapdomaindump/__init__.py", line 350, in mapGroupsIdsToDns
    gid = int(group.objectSid.value.split('-')[-1])
TypeError: a bytes-like object is required, not 'str'
`

The value where the exception is raised is the following: 
`
[*] Connecting as anonymous user, dumping will probably fail. Consider specifying a username/password to login with
[*] Connecting to host...
[*] Binding to host
[+] Bind OK
[*] Starting domain dump
group: DN: CN=test,OU=Security Groups,DC=htb,DC=local - STATUS: Read - READ TIME: 2020-02-06T06:24:31.554167
    cn: test
    dSCorePropagationData: 20200206113115.0Z
                           20200206113115.0Z
                           20200206113115.0Z
                           20200206113115.0Z
                           16010101000000.0Z
    distinguishedName: CN=test,OU=Security Groups,DC=htb,DC=local
    groupType: -2147483646
    instanceType: 4
    name: test
    objectCategory: CN=Group,CN=Schema,CN=Configuration,DC=htb,DC=local
    objectClass: top
                 group
    objectGUID: b'c\x8fp\x02\xfc\x84\x8bN\xa3\xf5\xc9Ec\x15\xdat'
    objectSid: b'\x01\x05\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00,\x1e%\xb7\x15u\xb2\x15\xc5\xb0\xf3O\xed\x13\x00\x00'
    sAMAccountName: test
    sAMAccountType: 268435456
`
Tried with the following versions:
LDAP Version: 2.5.1-0kali1
ldapdomaindump: 0.9.1-0kali2 (preinstalled) and 0.9.2 (from GIT)

**Comment by dirkjanm** [comment] 2020-02-06 11:41
Is this on HTB? Which host (then I can try to reproduce this myself)? Also are you using python2 or 3? Do you get the same error when you update ldap3?

**Comment by grease082** [comment] 2020-02-06 11:48
thanks for the fast response!

yes this is on htb. It is the forest machine.

I’m using python3!

With python2 I get the following error: 
root@kali:~/Downloads/ldapdomaindump# python2 ldapdomaindump.py 10.10.10.161
[*] Connecting as anonymous user, dumping will probably fail. Consider specifying a username/password to login with
[*] Connecting to host...
[*] Binding to host
[+] Bind OK
[*] Starting domain dump
Traceback (most recent call last):
  File "ldapdomaindump.py", line 3, in <module>
    ldapdomaindump.main()
  File "/root/Downloads/ldapdomaindump/ldapdomaindump/__init__.py", line 944, in main
    dd.domainDump()
  File "/root/Downloads/ldapdomaindump/ldapdomaindump/__init__.py", line 422, in domainDump
    rw.generateUsersReport(self)
  File "/root/Downloads/ldapdomaindump/ldapdomaindump/__init__.py", line 789, in generateUsersReport
    dd.mapGroupsIdsToDns()
  File "/root/Downloads/ldapdomaindump/ldapdomaindump/__init__.py", line 350, in mapGroupsIdsToDns
    gid = int(group.objectSid.value.split('-')[-1])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb7 in position 15: ordinal not in range(128)

Yes I get the same error after the update of ldap3!
<img width="958" alt="Screen Shot 2020-02-06 at 12 46 57" src="https://user-images.githubusercontent.com/6933380/73934580-02cb3480-48df-11ea-8c79-1b10437a9535.png">

**Comment by dirkjanm** [comment] 2020-02-06 12:31
This is probably a HTB specific thing. ldapdomaindump relies on the schema definitions to parse objects into a readable type. However I think the schema was (intentionally?) modified on this box, which makes the queries that try to load the schema fail. Therefor it doesn't decode the binary SID into a readable SID and thus it throws all kinds of errors. I could fix this specific instance but without the schema there will be many parts of the code that fail.

**Comment by grease082** [comment] 2020-02-06 12:44
Okay, thank you very much for the fast clarification. I'll query the domain in a different way then.

**Comment by dirkjanm** [comment] 2020-02-10 09:28
Closing this since dumping everything without access to the schema is not something that will be supported.

**Closed by dirkjanm** 2020-02-10 09:28 UTC
